### ISSUE TITLE
When the 1.4.4 update?

### ISSUE THREAD

**Issue by valeriialbertovich** [PlexusDuMenton/AnotherRpgMod#9]
Can someone give at least an approximate date? Like a month or something like that

**Comment by PlexusDuMenton** [comment]
Likely one year if there is ever an update

**Comment by valeriialbertovich** [comment]
They saying it can be soon but how soon?

**Comment by valeriialbertovich** [comment]
pease made it,and i heard someone making it,if it truth who it?and the author,please make update

**Comment by valeriialbertovich** [comment]
> Likely one year if there is ever an update

Can you ask somebody to port it please?

**Comment by valeriialbertovich** [comment]
Please update it
